name: Java CI with Gradle

on:
  push:
    branches: ['main', 'develop', 'release/*', 'hotfix/*']
  pull_request:
    branches: ['main', 'develop', 'release/*', 'hotfix/*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --no-daemon --stacktrace --info
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --no-daemon --stacktrace --info
